name: Build Docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '0 3 * * *'

env: 
  CARGO_TERM_COLOR: always

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tar curl
          rustup update stable && rustup default stable
      - name: Build the docs
        run: make all
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automatic Release"
          files: |
            docsets.tar.gz
            build/*.tgz
